version: '3.1'

services:
  app:
    container_name: springdemo
    image: springdemo
    build: ./
    ports:
      - "8080:8080"
      - "8443:443"
    depends_on:
      - postgres-db
      - keycloak

  postgres-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak
    ports:
      - "8090:8080"
    environment:
      - DB_USER=postgresadm
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
    depends_on:
      - postgres-db

volumes:
  postgres:
    external: false
